name: Build and Run Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  #------------------------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    #----------------------------------------------------------------------------------
    # Set up pre-requisite technology (Java 17, Gradle)
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'semeru'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.9'

    #----------------------------------------------------------------------------------
    - name: Checkout this repository
      uses: actions/checkout@v4
  
    #----------------------------------------------------------------------------------
    # Build and run the Simplatform application that the tests connect to
    - name: Checkout the Simplatform repository
      uses: actions/checkout@v4
      with:
        repository: jadecarino/simplatform
        path: ${{ github.workspace }}/simplatform

    - name: Build application
      working-directory: ${{ github.workspace }}/simplatform
      run: |
        ./build-locally.sh

    #----------------------------------------------------------------------------------
    # Build this Galasa test project
    - name: Build and publish to Maven local
      working-directory: ./dev.galasa.example
      run: |
        gradle clean build publishToMavenLocal

    #----------------------------------------------------------------------------------
    # Upload the local Maven repository so the next job can download it
    - name: Upload local maven repository
      uses: actions/upload-artifact@v4
      with:
        name: maven-local
        path: ~/.m2/repository


  #------------------------------------------------------------------------------------
  run-tests-with-galasactl:
    permissions:
      contents: read
    env:
      GALASA_HOME: ${{ github.workspace }}/.galasa
    runs-on: ubuntu-latest
    needs: build
    steps:

    #----------------------------------------------------------------------------------
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Download local Maven repository
      uses: actions/download-artifact@v4
      with:
        name: maven-local
        path: ${{ github.workspace }}/.m2/repository

    - name: Create credentials.properties file
      working-directory: ${{ env.GALASA_HOME }}
      run: |
        echo "${{ secrets.SIMBANK_CREDENTIALS }}" >> credentials.properties
    # The credentials.properties file should look something like this...
    # secure.credentials.MYSIMBANKUSER.username=XXX
    # secure.credentials.MYSIMBANKUSER.password=XXX

    #----------------------------------------------------------------------------------
    # Install Homebrew, then install galasactl
    - name: Install Homebrew
      run: |
        sudo apt-get update
        sudo apt-get install build-essential procps curl file git -y
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >>~/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      
    - name: Install galasactl with Homebrew
      run: |
        brew update
        brew install --no-quarantine galasactl

    #----------------------------------------------------------------------------------
    # Run the Galasa tests using "galasactl runs submit local" and upload test artifacts
    - name: Run the dev.galasa.example tests
      run: |
        echo "Starting SimBank application..."
        java -jar /github/workspace/.m2/repository/dev/galasa/galasa-simplatform/0.24.0/galasa-simplatform-0.24.0.jar &

        echo "Running SimBank tests..."

        galasactl runs submit local \
        --obr mvn:dev.galasa.example/dev.galasa.example.obr/0.0.1/obr \
        --class dev.galasa.example.simbank/dev.galasa.example.simbank.TestSimbank \
        --localMaven file:///github/workspace/.m2/repository \
        --log - || :

    # - name: Upload Galasa test results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: galasa-ras
    #     path: ${{ env.GALASA_HOME }}/ras