name: Build and Run Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  build-tests:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:

    #----------------------------------------------------------------------------------
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.9'
  
    #----------------------------------------------------------------------------------
    # Build the Simplatform application that the tests connect to
    - name: Checkout the Simplatform repository
      uses: actions/checkout@v4
      with:
        repository: jadecarino/simplatform
        path: ${{ github.workspace }}/simplatform

    - name: Build Simplatform application
      working-directory: ${{ github.workspace }}/simplatform
      run: |
        ./build-locally.sh

    #----------------------------------------------------------------------------------
    # Build this Galasa test project
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Build Galasa test project and publish to Maven local
      working-directory: ./dev.galasa.example
      run: |
        gradle clean build publishToMavenLocal

    #----------------------------------------------------------------------------------
    # Upload the local Maven repository so the next job can download it
    - name: Upload Maven local
      uses: actions/upload-artifact@v4
      with:
        name: maven-local
        path: ~/.m2/repository


  run-tests-with-galasactl:
    permissions:
      contents: read
    env:
      GALASA_HOME: ${{ github.workspace }}/.galasa
    runs-on: macos-latest
    needs: ["build-tests"]
    steps:

    #----------------------------------------------------------------------------------
    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'semeru'

    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Download Maven local
      uses: actions/download-artifact@v4
      with:
        name: maven-local
        # path: ${{ github.workspace }}/.m2/repository
        path: ~/.m2/repository

    - name: Create credentials.properties file
      working-directory: ${{ env.GALASA_HOME }}
      run: |
        echo "${{ secrets.SIMBANK_CREDENTIALS }}" >> credentials.properties

    # The credentials.properties file should look something like this:
    # secure.credentials.MYSIMBANKUSER.username=XXX
    # secure.credentials.MYSIMBANKUSER.password=XXX
    # Needs to be created dynamically as they cannot be checked into GitHub and exposed.

    #----------------------------------------------------------------------------------
    - name: Install galasactl with Homebrew
      run: |
        brew update
        brew tap galasa-dev/tap
        brew install --no-quarantine galasactl

    #----------------------------------------------------------------------------------
    - name: Initialise local Galasa environment
      run: |
        galasactl local init --log -

    #----------------------------------------------------------------------------------
    # Start the Simplatform application
    # The run the Galasa tests using "galasactl runs submit local"
    - name: Run the dev.galasa.example tests
      run: |
        echo "Starting SimBank application..."
        java -jar ~/.m2/repository/dev/galasa/galasa-simplatform/0.24.0/galasa-simplatform-0.24.0.jar &

        echo "Running SimBank tests..."

        galasactl runs submit local \
        --obr mvn:dev.galasa.example/dev.galasa.example.obr/0.0.1/obr \
        --class dev.galasa.example.simbank/dev.galasa.example.simbank.TestSimbank \
        --localMaven file:///Users/runner/.m2/repository \
        --log - || :

    - name: Upload Galasa test results
      uses: actions/upload-artifact@v4
      with:
        name: galasa-ras
        path: ${{ env.GALASA_HOME }}/ras