name: Build and Run Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  build-and-run-tests:
    runs-on: macos-latest
    permissions:
      contents: read
    env:
      GALASA_HOME: ${{ github.workspace }}/.galasa
    steps:

    #----------------------------------------------------------------------------------
    # Set up pre-requesite technology (Java, Gradle and galasactl)
    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'semeru'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.9'

    - name: Install galasactl with Homebrew
      run: |
        brew tap galasa-dev/tap
        brew install --no-quarantine galasactl
  
    #----------------------------------------------------------------------------------
    # Build the Simplatform application that the tests connect to
    - name: Checkout the Simplatform repository
      uses: actions/checkout@v4
      with:
        repository: jadecarino/simplatform
        path: ${{ github.workspace }}/simplatform

    - name: Build Simplatform application
      working-directory: ${{ github.workspace }}/simplatform
      run: |
        ./build-locally.sh

    #----------------------------------------------------------------------------------
    # Build this Galasa test project
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Build Galasa test project and publish to Maven local
      working-directory: ./dev.galasa.example.simbank
      run: |
        gradle clean build publishToMavenLocal

    #----------------------------------------------------------------------------------
    # Set up Galasa environment
    - name: Create credentials.properties file
      working-directory: ${{ env.GALASA_HOME }}
      run: |
        echo "${{ secrets.SIMBANK_CREDENTIALS }}" >> credentials.properties
  
      # The credentials.properties file should look something like this:
      # secure.credentials.MYSIMBANKUSER.username=XXX
      # secure.credentials.MYSIMBANKUSER.password=XXX
      # Needs to be created dynamically as they cannot be checked into GitHub and exposed.

    - name: Initialise local Galasa environment to create remaining files and folders
      run: |
        galasactl local init --log -

    #----------------------------------------------------------------------------------
    # Run the Simplatform application 
    - name: Start the Simplatform application
      run: |
        echo "Starting SimBank application..."

        java -jar /Users/runner/.m2/repository/dev/galasa/galasa-simplatform/0.24.0/galasa-simplatform-0.24.0.jar &
    
    #----------------------------------------------------------------------------------
    # Run the Galasa tests
    - name: Run the dev.galasa.example.simbank tests
      run: |
        echo "Running SimBank tests..."

        galasactl runs submit local \
        --obr mvn:dev.galasa.example.simbank/dev.galasa.example.simbank.obr/0.0.1-SNAPSHOT/obr \
        --class dev.galasa.example.simbank.login/dev.galasa.example.simbank.login.TestLogin \
        --localMaven file:///Users/runner/.m2/repository \
        --log - || :
    
    #----------------------------------------------------------------------------------
    # Upload the Galasa test results as an artifact so they can be downloaded from GitHub
    - name: Upload Galasa test results
      uses: actions/upload-artifact@v4
      with:
        name: galasa-ras
        path: ${{ env.GALASA_HOME }}/ras